# Generated by Django 3.2.9 on 2022-01-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='address',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='bio',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
