# Generated by Django 3.2.9 on 2022-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-finish_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-finish_date']},
        ),
        migrations.RemoveField(
            model_name='education',
            name='education_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_year',
        ),
        migrations.AddField(
            model_name='education',
            name='finish_date',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='finish_date',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
